// <auto-generated />
using System;
using HospitalDoctorManagement.Infrastructure.Persistance.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HospitalDoctorManagement.Infrastructure.Persistance.Migrations
{
    [DbContext(typeof(HospitalDoctorDbContext))]
    [Migration("20240508161552_İnit")]
    partial class İnit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DoctorHospital", b =>
                {
                    b.Property<Guid>("DoctorsDoctorID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HospitalsHospitalID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DoctorsDoctorID", "HospitalsHospitalID");

                    b.HasIndex("HospitalsHospitalID");

                    b.ToTable("DoctorHospital");
                });

            modelBuilder.Entity("HospitalDoctorManagement.Api.Core.Domain.Model.Doctor", b =>
                {
                    b.Property<Guid>("DoctorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DoctorID");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("HospitalDoctorManagement.Api.Core.Domain.Model.Hospital", b =>
                {
                    b.Property<Guid>("HospitalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HospitalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HospitalID");

                    b.ToTable("Hospitals");
                });

            modelBuilder.Entity("DoctorHospital", b =>
                {
                    b.HasOne("HospitalDoctorManagement.Api.Core.Domain.Model.Doctor", null)
                        .WithMany()
                        .HasForeignKey("DoctorsDoctorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalDoctorManagement.Api.Core.Domain.Model.Hospital", null)
                        .WithMany()
                        .HasForeignKey("HospitalsHospitalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
